# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-24 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender_spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_id', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
                ('start_time', models.CharField(max_length=250)),
                ('ad_image', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='My_Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=250)),
                ('website_placement', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='calender_spot',
            name='My_Calender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.My_Calender'),
        ),
    ]
