# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-31 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_calender_spot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_calender',
            name='calender_image',
            field=models.CharField(default='open', max_length=250),
        ),
    ]
